name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-bionic-cuda11_6-py3_10-gcc7-build:
    name: linux-bionic-cuda11.6-py3.10-gcc7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.6-py3.10-gcc7
      docker-image-name: pytorch-linux-bionic-cuda11.6-cudnn8-py3-gcc7

  linux-bionic-cuda11_6-py3_10-gcc7-test:
    name: linux-bionic-cuda11.6-py3.10-gcc7
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_6-py3_10-gcc7-build
    with:
      build-environment: linux-bionic-cuda11.6-py3.10-gcc7
      docker-image: ${{ needs.linux-bionic-cuda11_6-py3_10-gcc7-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
        ]}
